file_format: "1"
id: cornefx
name: CorneFx
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - cornefx_left
  - cornefx_right
